version: '3.8'

services:
  # BASE DE DATOS
  db:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata:/app/dbdata
  server:
    build: .
    volumes:
      - ./src:/app/src
    command: npm run dev
    ports:
      - '4000:4000'
    depends_on:
      - db
